# -*- coding: utf-8 -*-
"""references.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V22hUBbBzA7s8C9CsRpopYcNiEJURQZ0
"""

print("Welcome to Final Project for Hacktech. This is created by Amit Kumar Singh (aksmlibts@gmail.com)")

#Cloning my GitHub repo
!git clone https://github.com/itheaks/HackTech_Final.git

# Commented out IPython magic to ensure Python compatibility.
#Lets move to our required Directory
# %cd /content/HackTech_Final

#Installing the required directory
!pip install -e '.[dev]'

# Commented out IPython magic to ensure Python compatibility.
#As I have used yolov8 model so lets move to the required directory
# %cd /content/HackTech_Final/ultralytics/yolo/v8/detect

#Lets download our DeepSort pytorch File
!gdown "https://drive.google.com/uc?id=11ZSZcG-bcbueXZC3rN08CM0qqX3eiHxf&confirm=t"

#Unzipping deep_sort_pytorch.zip
!unzip 'deep_sort_pytorch.zip'

#Lets setup our main predict while where all the code of speed estimation is available
!gdown "https://drive.google.com/uc?id=1oNJHwF1l3wWx2fV_uvLbS_jwSbmo06AI"

#To test lets connect our google drive and import the videos.
from google.colab import drive
drive.mount('/content/drive')

!python predict.py model=yolov8n.pt source="/content/drive/MyDrive/Amit Kumar Singh Final Submission HackTech/Given Videos/"

#Feel free to download from the location as "/content/HackTech_Final/runs/detect/train"

#This all is for here thank you

print("Thank you")

#Contact info aksmlibts@gmail.com